apiVersion: v1
kind: Service
metadata:
  name: admin-ui
  labels:
    app: admin-ui
spec:
  type: LoadBalancer
  selector:
    app: admin-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
